version: '3'
services:
  p4d:
    build: docker
    image: ghcr.io/yaegashi/p4d-docker/p4d
    environment:
      SERVERID: master
    ports:
      - 1666:1666
    volumes:
      - ./perforce/servers:/opt/perforce/servers
